[WIP] Sidenav links and Color Page
pluralsight/design-system pull request #1132
Opened 2020-09-03 23:02 UTC by jaketrent

asdf

2020-09-08 21:14 UTC, danethurber requested changes
just one nitpick. the truncation of the variable name is gross. can we find a better way to do it

![Screen Shot 2020-09-08 at 3 13 29 PM](https://user-images.githubusercontent.com/226356/92528430-f943db00-f1e5-11ea-8dbb-e02775c49a11.png)

2020-09-08 21:15 UTC, jaketrent commented
@danethurber yes, we can look at better ways to make that all fit.  Can we merge the old design before we redesign?

2020-09-08 21:29 UTC, danethurber approved these changes

2020-09-08 21:43 UTC, jaketrent commented
@danethurber what do you think of this redesign? https://github.com/pluralsight/design-system/pull/1132/commits/fe3d11fc9308964654205c0d36e602e2eabe878c

Adds more horz space for var names. Adds JS name in too.

If we go with it, I should probably tweak the rest of the page to match.

2020-09-08 21:48 UTC, danethurber commented on docs/src/components/typography/font-weight.tsx
> +            <div>CS: {w.varName}</div>
```suggestion
            <div>CSS: {w.varName}</div>
```

2020-09-08 21:48 UTC, danethurber approved these changes
it works for me. @sweeting should probably chime in

2020-09-08 21:50 UTC, jaketrent commented
@sweeting do you like this new design for the font weight section? or keep the old (see above)? or create something original and fresh?

<img width="1030" alt="Screen Shot 2020-09-08 at 3 49 46 PM" src="https://user-images.githubusercontent.com/552044/92531180-0911ee00-f1eb-11ea-805d-41e851ed1c8f.png">

2020-09-09 15:33 UTC, sweeting commented
Yeah, that accommodates the space for the variables without truncating. Let's use this style for the variables. 
![image](https://user-images.githubusercontent.com/48542/92620149-8dae4c00-f27f-11ea-8d16-5115bc9b3365.png)

2020-09-09 16:04 UTC, merged