variable font playground
pluralsight/design-system pull request #1478
Opened 2020-11-30 13:46 UTC by jaketrent

- Added example we used with TypeType
- Move examples/ into packages/ so that linking will work (of course, now that we have yarn workspaces doing the linking, maybe this isn't required (a la docs)).  Somebody correct me on this if not needed.

2020-11-30 16:33 UTC, danethurber commented
you could also add the `examples` dir to the workspaces and lerna config

2020-11-30 16:34 UTC, jaketrent commented
would that be your preference? ^

2020-11-30 16:36 UTC, danethurber commented
yes that would be my pref. also the current implementation doesn't work because the projects are nested inside packages/examples. for yarn linking they would need to NOT be nested since our config just looks at the packages/* dir

2020-11-30 16:46 UTC, danethurber requested changes
i'm holding of on reviewing until the examples find their new home. i'm unable to run a `yarn build` from the root. i'm getting a error

2020-12-01 12:45 UTC, jaketrent commented
@danethurber examples moved back to root, added to lerna config for linking, and root build looks good.  Please have a re-look.

2020-12-01 16:12 UTC, danethurber requested changes
please review/merge my pr -> https://github.com/pluralsight/design-system/pull/1483

2020-12-01 16:12 UTC, danethurber commented on examples/variable-font/README.md
> +├── fonts
we should .gitignore this folder just to be safe

2020-12-01 16:12 UTC, danethurber commented on examples/variable-font/README.md
> +│       └── PS_TT_Commons_Var_Roman-VF.woff2
FYI. these filenames are slightly different than the files i have

2020-12-01 19:52 UTC, jaketrent commented
Hey @danethurber , I somehow hosed your #1483 branch.

I just ran `git cherry-pick b301ddc5f25408cf78f23709163f5cb92c0b465e` on this branch.  Should be good to roll now. 

Please re-review.

2020-12-01 19:53 UTC, danethurber approved these changes

2020-12-01 21:05 UTC, merged