convert components to use new core type vars
pluralsight/design-system pull request #1570
Opened 2021-01-21 17:27 UTC by jaketrent

## Font size

- [x] add 1000: 56px
- [x] add 1100: 72px
- [x] add 1200: 88px
- [x] fontSizeGigantic -> (unused)
- [x] fontSizeJumbo ->  Figma design change
  - [x] avatar - 
- [x] fontSizeXXLarge -> Figma design change
  - [x] avatar
  - [x] datawell
- [x] fontSizeXLarge -> (unused)
- [x] fontSizeLarge -> fontSize600
- [x] fontSizeMedium -> fontSize400
- [x] 16px -> fontSizeBase
- [x] fontSizeSmall -> fontSize200
- [x] fontSizeXSmall -> fontSize100

## Letter spacing

- [x] letterSpacingGigantic -> (unused)
- [x] letterSpacingJumbo -> (unused)
- [x] letterSpacingXXLarge -> (unused)
- [x] letterSpacingXLarge -> (unused)
- [x] letterSpacingLarge -> Figma design change
  - [x] emptystate
  - [x] errors
- [x] letterSpacingMedium -> (unused)
- [x] letterSpacingSmall -> Figma design change
  - [x] emptystate
  - [x] errors
- [x] letterSpacingXSmall -> (unused)

## Font weight

- [x] fontWeightBlack -> fontWeight900
- [x] fontWeightXBold -> fontWeight800
- [x] fontWeightBold -> fontWeight700
- [x] fontWeightDemiBold -> fontWeightStrong
- [x] fontWeightMedium -> fontWeight500
- [x] fontWeightRegular -> fontWeightDefault
- [x] fontWeightBook -> fontWeightDefault
- [x] fontWeightLight -> fontWeight300
- [x] fontWeightXLight -> fontWeight200
- [x] fontWeightThin -> fontWeight100

## Line height

- [x] lineHeightTight -> (remains)
- [x] lineHeightStandard -> (remains)
- [x] lineHeightExtra -> (remains)
- [x] lineHeightHuge -> (remains)

2021-01-22 16:22 UTC, danethurber reviewed
everything looks good to me. i'm not approving since I think @sweeting should do that - but 👍  from me

2021-01-22 16:22 UTC, danethurber commented on commit.sh
> +done
did you mean to add this to vcs

2021-01-22 16:29 UTC, jaketrent commented on commit.sh
> +done
lol, nope.  Will rm. Thanks.

2021-01-23 00:04 UTC, sweeting requested changes
- Made a few adjustments to match some design changes in Figma.
- Changed all references to `fontWeight700` to `fontWeightStrong`

2021-01-23 00:04 UTC, sweeting commented on packages/table/src/css/index.ts
> +      fontWeight: type.fontWeight700,
```suggestion
      fontWeight: type.fontWeightStrong,
```

2021-01-23 00:04 UTC, sweeting commented on packages/verticaltabs/src/css/index.ts
> +    fontWeight: type.fontWeight700,
```suggestion
    fontWeight: type.fontWeightStrong,
```

2021-01-25 16:26 UTC, jaketrent commented
Hey @sweeting , I took all your changes and committed them.  Please re-review.

2021-01-25 16:27 UTC, sweeting approved these changes
👍

2021-01-25 20:04 UTC, merged