refactor(util): useCloseOnDocumentEvents triggers callback when scroll outside of menu
pluralsight/design-system pull request #1748
Opened 2021-05-12 20:18 UTC by jaketrent

Does this seem like the write general solution? 

I intend the code to be: Use the hook to close the menu when events are triggered *outside* of the menu. Resize will always be. Click might be in or out. We have had a check for if the click is within the menu. We haven't had that for scroll. Seems like we need to do the same check.

If this seems like the right way to go, I think I'd like to revert the recent patch to Dropdown to rely on this, if possible.

2021-05-13 18:48 UTC, EdwardIrby requested changes
Please look at Select stories. It seems like the first three stories are now broken. I'd prefer maybe just copying this into dropdown and using it separate as this effects both Menu and Select components.

2021-05-13 18:48 UTC, EdwardIrby commented on packages/util/src/use-close-on-document-events.ts
>    const handleClickOutsideMenu = (evt: MouseEvent) => {
evt: Event | UIEvent

2021-05-13 18:48 UTC, EdwardIrby commented on packages/util/src/use-close-on-document-events.ts
> +  const handleScrollOutsideMenu = (evt: MouseEvent) => {
evt: Event | UIEvent

2021-05-14 22:35 UTC, jaketrent commented
@EdwardIrby Good call on the Select story effects. I didn't catch that.

In this iteration, I felt like we should keep these event handler hooks centralized in util because of the vast reusability. But that breaking them up into separate events and  callbacks would allow for more flexibility in their application.

Please have another review.

2021-05-18 21:14 UTC, EdwardIrby approved these changes

2021-05-20 14:48 UTC, merged