CSS build support and Avatar CSS conversion
pluralsight/design-system pull request #1818
Opened 2021-06-18 22:23 UTC by jaketrent

Fixed JS->CSS build which had been broken since ESM. Added scripts to Build for reuse. Exposed refactor helper in Core. Used Storybook postcss preset. 

What do you think of the utils?
How about the conversion itself?

2021-06-18 22:26 UTC, jaketrent commented on packages/avatar/src/css/index.css
> +  /* TODO: revert to bg util color after it exists in css vars */
see https://github.com/pluralsight/design-system/issues/1817

2021-06-18 22:33 UTC, EdwardIrby commented
@jaketrent we should probably have @sweeting look at these going forward for visual errors that test can not catch.

2021-06-21 18:25 UTC, EdwardIrby requested changes
Seeing the following warning message when running build in Avatar
`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`

Further we need to build to a path relative to the index.js files in the esm and cjs directories. 
- `dist/cjs/css/index.css`
- `dist/esm/css/index.css`

Storybook wouldn't show these failing nor our test but for the distributed packages we want them at these locations.

2021-06-21 18:25 UTC, EdwardIrby commented
Visually looks the same as the glamor variant!

2021-06-21 19:54 UTC, jaketrent commented
@EdwardIrby Thanks for the review. Good catch on the postcss plugin missing. 

I'm not thrilled with having the css under the `dist/esm` and `dist/cjs` subdirs. The `index.css` file is not of that tech and thus seems wrongly categorized. I know that this is for the `dist` dir to be able to relative import like the `src` dir. I don't have another solution in mind yet.

2021-06-22 17:00 UTC, merged