css/tooltip-text
pluralsight/design-system pull request #1883
Opened 2021-07-01 09:12 UTC by EdwardIrby

resolve #1875 
resolve #1877 
resolve #1878 
resolve #1879

2021-07-01 15:00 UTC, jaketrent requested changes
Found several things that could use an update.

2021-07-01 15:00 UTC, jaketrent commented on packages/text/src/react/__specs__/heading.spec.tsx
> +    it('composes className', () => {
With the addition of this an other specs, I think the "Class Override" stories could safely be removed.

2021-07-01 20:43 UTC, EdwardIrby commented on packages/textinput/src/react/index.tsx
> +              })}
I'll try to do that going forward.

2021-07-02 00:11 UTC, EdwardIrby commented on packages/text/src/css/index.css
> +.psds-text__label--size-xSmall {
I just realized we have a dashify utility. I've been converting these manually in the style sheets and vars. Let me know what you think of the change to vars on tooltip and text

2021-07-02 22:37 UTC, sweeting requested changes
Tooltip, TextInput, Textarea look good.

Text: I didn't see size stories for label and the only size of label I see was wrapped in an `<h1>` and font-size is 32px.

Specs for the text label components can be found in [this Figma file](https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/PSDS-Web-Components?node-id=11732%3A50314).

![image](https://user-images.githubusercontent.com/48542/124334069-330a1780-db53-11eb-919a-cd7cbfcc6c14.png)

2021-07-06 17:18 UTC, EdwardIrby commented
> this Figma file

I'll go ahead and see what's up with these. Thanks!

2021-07-07 16:37 UTC, jaketrent commented
Not sure if it'll make a diff here or not, but I saw that master was back merged. I think we should avoid that. This is a branch to merge into convertScript. I would advise only back-merging convertScript at this point.

2021-07-07 16:43 UTC, merged