Css/tagsinput switch
pluralsight/design-system pull request #1901
Opened 2021-07-07 16:53 UTC by EdwardIrby

resolves #1895
resolves #1896
resolves #1897
resolves #1898 
resolves #1899

2021-07-07 16:55 UTC, jaketrent commented
I'll take a look at this. Why are there old, unrelated commits in this new branch?

2021-07-07 17:40 UTC, jaketrent requested changes

2021-07-07 17:40 UTC, jaketrent commented on packages/tab/src/react/list-item.tsx
> +        className: classNames(
This is an exported sub-component. Please add className composition.

2021-07-07 17:40 UTC, jaketrent commented on packages/tab/src/react/list.tsx
> +        className,
I would compose last.

2021-07-07 17:40 UTC, jaketrent commented on packages/table/src/css/index.css
> +null.psds-table__container {
please cleanup.

2021-07-07 17:40 UTC, jaketrent commented on packages/table/src/css/index.css
> +null.psds-table__header__sort-icon.psds-table__header__sort-icon {
cleanup and dedup

2021-07-07 17:40 UTC, jaketrent commented on packages/table/src/react/index.tsx
> +        className,
would compose last.

there are a few more, so I'm going to stop marking these.

2021-07-07 17:40 UTC, jaketrent commented on packages/tag/src/css/index.css
> +.psds-tag--isPressed {
dashify

2021-07-07 17:40 UTC, jaketrent commented on packages/tagsinput/src/css/index.css
> +null.psds-tagsinput {
cleanup

2021-07-07 17:40 UTC, jaketrent commented on packages/tagsinput/src/css/index.css
> +  display: -webkit-box;
vendor-specific not needed

2021-07-07 17:40 UTC, jaketrent commented on packages/text/src/css/index.ts
> +import {
this seems like a mistake to be re-appearing.

2021-07-07 19:58 UTC, sweeting requested changes
@EdwardIrby  

Did a visual check on:
✅ switch
✅ tab
✅ table
✅ tag
⛔ tagsinput

tagsinput: looks like the text & icon color in the tags is getting turned dark somewhere.
![CleanShot 2021-07-07 at 13 52 27](https://user-images.githubusercontent.com/48542/124821006-679f1a00-df2b-11eb-9809-43e2d7f14d06.png)

2021-07-07 20:44 UTC, EdwardIrby commented on packages/switch/src/react/index.tsx
> +          className,
The order in which the attributes are overwritten is not determined by the order the classes are defined in the class attribute, but instead where they appear in the CSS.

2021-07-08 18:04 UTC, sweeting requested changes
tagsinput: Still seeing the dark text & icons in the blue tags.

2021-07-08 18:22 UTC, sweeting approved these changes
👍 
![CleanShot 2021-07-08 at 12 21 40](https://user-images.githubusercontent.com/48542/124972003-148a9d00-dfe7-11eb-8493-83e58b521ce6.png)

2021-07-08 19:12 UTC, jaketrent approved these changes

2021-07-08 19:13 UTC, merged