Css/navitem multiselect
pluralsight/design-system pull request #1936
Opened 2021-07-15 06:38 UTC by EdwardIrby

resolves #1916 
resolves #1917 
resolves #1918 
resolves #1919 
resolves #1920

2021-07-15 20:40 UTC, jaketrent requested changes
Not sure how this happened. The camelCase psds core vars are incorrect. They need dashified. Maybe something weird with the version of the update script?? Anyway, storybook confirms that these have lots of visual issues. I think getting the vars fixed up is priority 1.

2021-07-15 20:40 UTC, jaketrent commented on packages/navbar/src/css/index.css
> +.psds-navbar {;
```suggestion
.psds-navbar {
```

2021-07-15 20:40 UTC, jaketrent commented on packages/navbar/src/css/index.css
> +  padding: var(--psLayoutSpacingXSmall);
ps var problem again -- needs dashify

2021-07-15 20:40 UTC, jaketrent commented on packages/navbrand/src/react/index.tsx
> +      Boolean(props.children) && 'psds-navbrand__logo--wordmark'
Not sure it's any safer, but `React.Children.count(props.children) > 0` comes to mind.

2021-07-16 21:09 UTC, jaketrent requested changes
Code good to my eye. 

There's something wrong with Multiselect. It's a 2-rower. Not so in master. I did a rebuild. Must be something going on in CSS? Anyone else seeing the same?

<img width="426" alt="Screen Shot 2021-07-16 at 2 48 12 PM" src="https://user-images.githubusercontent.com/552044/126008802-4a54ee09-7ab4-4184-90e7-a8724d29f73a.png">

2021-07-19 22:45 UTC, sweeting requested changes
Reviewed all visually and the only issue I noticed was the one [Jake mentioned](https://github.com/pluralsight/design-system/pull/1936#pullrequestreview-708750359) regarding the double height by default on the multiselect.

Jake created a [PR](https://github.com/pluralsight/design-system/pull/1940) that fixes that issue and I reviewed that and it looks correct.

2021-07-21 05:25 UTC, EdwardIrby commented
Fixed the double row thing though it made some things clear about the Field component and styles. Let's chat about this tomorrow morning.

2021-07-21 19:03 UTC, sweeting approved these changes
Multiselect looks good to me now.

2021-07-21 20:01 UTC, jaketrent commented on packages/multiselect/src/css/index.css
> +.psds-multi-select__input-container>.psds-field__input {
nit: I'd put spaces around the child combinator, stylistically treating it like other operators. I'm surprised prettier didn't do this. But then, maybe prettier isn't running on our css.

2021-07-21 20:01 UTC, jaketrent approved these changes

2021-07-22 00:32 UTC, merged